import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import docx
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

# --- DATA SETS ---

# 1. PTA CLIN REAJUSTE (55 activities aligned with PTA BUDGETISE reference)
PTA_CLIN_REAJUSTE_DATA = [
    # OS I. PROGRAMME PCI
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.1 Rédiger le cahier de charge de l’Équipe Opérationnelle de PCI (EOPCI)",
        "resp": "Point focal PCI / EOPCI / DG",
        "per": "Septembre 2026",
        "ind_base": "Cahier des charges inexistant ou non formalisé",
        "ind_cible": "Cahier des charges rédigé, validé et archivé",
        "source": "Néant",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.2. Restructurer l’Équipe Opérationnelle de PCI (EOPCI)",
        "resp": "DG / Point focal PCI",
        "per": "Octobre 2026",
        "ind_base": "Composition antérieure nécessitant réajustement",
        "ind_cible": "Note de service portant restructuration de l'EOPCI signée",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.3. Renouveler la note de service portant nomination du Point focal PCI",
        "resp": "DG / Point focal PCI",
        "per": "Octobre 2026",
        "ind_base": "Note de nomination échue",
        "ind_cible": "Note de service de reconduction signée par la DG",
        "source": "Néant",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.4. Restructurer le Comité de Lutte contre les Infections Nosocomiales (CLIN)",
        "resp": "DG / CLIN",
        "per": "Octobre 2026",
        "ind_base": "Mandat des membres arrivé à échéance",
        "ind_cible": "Note de service portant composition actualisée du CLIN signée",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.5. Nommer l’équipe des formateurs internes en PCI du CHUMEL",
        "resp": "DG / Point focal PCI / EOPCI",
        "per": "Octobre 2026",
        "ind_base": "Pool de formateurs non formalisé",
        "ind_cible": "Note de service désignant les formateurs internes en PCI disponible",
        "source": "Néant",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "1.1.6. Nommer les points focaux IAS-PCI (binôme soignant et technicien d'hygiène par service)",
        "resp": "EOPCI / DG",
        "per": "Octobre 2026",
        "ind_base": "Absence de réseau formel de relais dans chaque unité de soins",
        "ind_cible": "Note de service désignant les binômes de points focaux dans 100% des services",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.1. Renforcement de la gouvernance et de la structure institutionnelle de PCI",
        "act": "Solliciter une expertise externe pour accompagner le CLIN/PCI",
        "resp": "DG / CLIN / EOPCI",
        "per": "Février 2027",
        "ind_base": "Absence d'accompagnement externe d'audit et d'expertise PCI",
        "ind_cible": "1 mission d'expertise externe réalisée avec rapport d'évaluation et recommandations stratégiques",
        "source": "FP",
        "rec": False,
        "bud": 2100000,
        "bud_detail": "Honoraires et mission expert externe PCI (Forfait global)"
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.1. Organiser les réunions hebdomadaires de l’équipe opérationnelle de PCI (EOPCI)",
        "resp": "Point focal / EOPCI",
        "per": "Hebdomadaire (Oct. 2026 - Sept. 2027)",
        "ind_base": "Réunions d'équipe irrégulières",
        "ind_cible": "48 à 52 comptes-rendus de réunions hebdomadaires disponibles",
        "source": "FP / Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.2. Organiser les réunions trimestrielles du Comité de Lutte contre les Infections Nosocomiales (CLIN)",
        "resp": "Président CLIN / Point focal PCI",
        "per": "Trimestriel (Déc. 2026, Mars, Juin, Sept. 2027)",
        "ind_base": "CLIN réuni de façon sporadique",
        "ind_cible": "4 sessions statutaires du CLIN tenues avec PV de délibération",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.3. Assurer le suivi rapproché de la mise en œuvre des décisions du CLIN et de l'EOPCI",
        "resp": "EOPCI / DAF / Direction des Soins",
        "per": "Continu",
        "ind_base": "Faible traçabilité de l'exécution des résolutions",
        "ind_cible": "Tableau de bord trimestriel de suivi des recommandations renseigné à 100%",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.4. Élaborer le Plan de Travail Annuel (PTA) et le budget PCI",
        "resp": "Point focal / EOPCI",
        "per": "Octobre 2026",
        "ind_base": "Plan d'action antérieur échu",
        "ind_cible": "Document complet du PTA et budget PCI rédigé et disponible",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "Organiser l’atelier de Validation du plan stratégique, du PTA, du PO et du budget",
        "resp": "DG / CLIN / Point focal PCI",
        "per": "Octobre 2026",
        "ind_base": "Projets de plan stratégique, PTA, PO et budget non validés",
        "ind_cible": "Plan stratégique, PTA, PO et budget validés par acte officiel",
        "source": "FP",
        "rec": True,
        "bud": 200000,
        "bud_detail": "25 participants x 8 000 FCFA (indemnités & pause-café atelier)"
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.5. Approuver officiellement le plan élaboré selon les exigences de la Direction Générale",
        "resp": "DG",
        "per": "Décembre 2026",
        "ind_base": "PTA validé en atelier mais non encore formalisé par décision",
        "ind_cible": "PTA officiellement approuvé par décision de la Direction Générale",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.6. Disséminer et vulgariser le PTA PCI auprès de l'ensemble des départements et pôles",
        "resp": "Point focal / EOPCI",
        "per": "Janvier 2027",
        "ind_base": "PTA non vulgarisé auprès des chefs de pôle et majors",
        "ind_cible": "Bordereau de transmission et séances de briefing tenues dans tous les pôles",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "I. PROGRAMME PCI",
        "inter": "1.2. Fonctionnement, animation et planification du programme PCI",
        "act": "1.2.7. Intégrer le PTA et le budget PCI au Plan Intégré de Travail et Budget Annuel (PITBA) de l'hôpital",
        "resp": "DG / DAF / Point focal PCI",
        "per": "Janvier 2027",
        "ind_base": "Lignes budgétaires PCI dispersées",
        "ind_cible": "Lignes budgétaires PCI sanctuarisées dans le budget consolidé de l'hôpital",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },

    # OS II. LIGNES DIRECTRICES, PROTOCOLES ET POS
    {
        "os": "II. LIGNES DIRECTRICES, PROTOCOLES ET POS",
        "inter": "2.1. Élaboration, révision et diffusion des lignes directrices et Procédures Opérationnelles Standardisées (POS)",
        "act": "Réaliser la relecture des lignes directrices nationales et internationales (OMS) de PCI et les adapter au contexte du CHUMEL",
        "resp": "EOPCI / CLIN",
        "per": "2 Jours Décembre 2026 - Janvier 2027",
        "ind_base": "Lignes directrices non adaptées aux réalités médico-techniques actuelles",
        "ind_cible": "Rapport d'analyse comparative et guide institutionnel de PCI adapté",
        "source": "FP",
        "rec": False,
        "bud": 240000,
        "bud_detail": "15 experts x 8 000 FCFA/j x 2 jours de relecture et contextualisation"
    },
    {
        "os": "II. LIGNES DIRECTRICES, PROTOCOLES ET POS",
        "inter": "2.1. Élaboration, révision et diffusion des lignes directrices et Procédures Opérationnelles Standardisées (POS)",
        "act": "2.1.2. Élaborer, réviser et standardiser le corpus des Procédures Opérationnelles Standardisées (POS) prioritaires :\n1- POS Bionettoyage des locaux, blocs opératoires et néonatologie\n2- POS Cathétérisme veineux périphérique et central\n3- POS Sondage vésical à demeure et soins de sonde\n4- POS Hygiène des mains (lavage simple, hygiénique et friction)\n5- POS Tri, collecte et stockage des Déchets Biomédicaux (DBM)\n6- POS Conduite à tenir en cas d'Accident d'Exposition au Sang (AES)\n7- POS Préparation et contrôle des antiseptiques et désinfectants",
        "resp": "EOPCI / Comité de rédaction (8 experts)",
        "per": "Décembre 2026 - Janvier 2027",
        "ind_base": "POS parcellaires, non harmonisées ou non écrites",
        "ind_cible": "Recueil validé de 7 POS prioritaires standardisées",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "II. LIGNES DIRECTRICES, PROTOCOLES ET POS",
        "inter": "2.1. Élaboration, révision et diffusion des lignes directrices et Procédures Opérationnelles Standardisées (POS)",
        "act": "2.1.3. Organiser une séance statutaire de validation technique des POS élaborées par le CLIN et la direction",
        "resp": "CLIN / DG",
        "per": "Février 2027",
        "ind_base": "Projets de POS rédigés sans validation formelle",
        "ind_cible": "Procès-verbal de validation technique signé par le Président du CLIN et la DG",
        "source": "FP",
        "rec": False,
        "bud": 200000,
        "bud_detail": "25 participants x 8 000 FCFA (indemnités & pause-café de validation)"
    },
    {
        "os": "II. LIGNES DIRECTRICES, PROTOCOLES ET POS",
        "inter": "2.1. Élaboration, révision et diffusion des lignes directrices et Procédures Opérationnelles Standardisées (POS)",
        "act": "2.1.4. Mettre à disposition, reproduire et plastifier les classeurs de POS et fiches réflexes dans l'ensemble des services de soins",
        "resp": "EOPCI / Économat",
        "per": "Mars 2027",
        "ind_base": "Absence de classeurs de POS opérationnels aux postes de soins",
        "ind_cible": "20 classeurs complets de POS et fiches réflexes plastifiées disposés aux postes de soins",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "II. LIGNES DIRECTRICES, PROTOCOLES ET POS",
        "inter": "2.1. Élaboration, révision et diffusion des lignes directrices et Procédures Opérationnelles Standardisées (POS)",
        "act": "2.1.5. Conduire des séances de briefing et d'appropriation des POS auprès du personnel soignant des pôles",
        "resp": "Formateurs internes / EOPCI",
        "per": "Mars - Avril 2027",
        "ind_base": "Méconnaissance des protocoles par le personnel exécutant",
        "ind_cible": "Au moins 80% des équipes soignantes briffées sur les nouvelles POS",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },

    # OS III. FORMATION ET ÉDUCATION EN PCI
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "3.1.1. Faire un planning annuel de formation du personnel hospitalier en PCI :\n- Recueillir et analyser les besoins en formation\n- Élaborer les modules pédagogiques et le calendrier annuel",
        "resp": "Point focal / EOPCI",
        "per": "Novembre 2026",
        "ind_base": "Formations antérieures non programmées",
        "ind_cible": "Plan annuel de formation PCI validé et notifié aux services",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "3.1.2. Faire un planning de formation continue et de perfectionnement pour l'équipe PCI et les formateurs internes",
        "resp": "Point focal / CLIN",
        "per": "Décembre 2026",
        "ind_base": "Mise à jour hétérogène des compétences des encadreurs",
        "ind_cible": "Planning de formation de formateurs formalisé",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "Faire former 3 personnels du CLIN en hygiène hospitalière PCI et sécurité des patients",
        "resp": "DG / CLIN / EOPCI",
        "per": "Janvier - Mars 2027",
        "ind_base": "Compétences pointues à renforcer au sein du CLIN",
        "ind_cible": "3 membres du CLIN certifiés en hygiène hospitalière et sécurité des patients",
        "source": "FP",
        "rec": False,
        "bud": 1500000,
        "bud_detail": "3 inscriptions / bourses certifiantes x 500 000 FCFA"
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "Faire former 1 personnel du CLIN en évaluation des risques sanitaires",
        "resp": "DG / CLIN / EOPCI",
        "per": "Janvier - Mars 2027",
        "ind_base": "Absence de cadre formé spécifiquement à la cartographie des risques infectieux",
        "ind_cible": "1 cadre du CLIN certifié en évaluation des risques sanitaires hospitaliers",
        "source": "FP",
        "rec": False,
        "bud": 500000,
        "bud_detail": "1 inscription / formation certifiante en gestion des risques sanitaires"
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "3.1.3. Former l'ensemble du personnel soignant aux Précautions Standard et Précautions Complémentaires une fois par an (focus COVID-19, Fièvre de Lassa, Mpox) :\n- Diffuser les notes de service et plannings de passage\n- Dispenser les sessions modulaires (300 professionnels ciblés)\n- Réaliser les pré-tests et post-tests de compétences",
        "resp": "Formateurs internes / EOPCI / DG",
        "per": "Janvier - Mars 2027",
        "ind_base": "Personnel soignant non recyclé aux précautions standard",
        "ind_cible": "Au moins 300 soignants formés avec gain moyen de compétences > 40%",
        "source": "FP",
        "rec": True,
        "bud": 2400000,
        "bud_detail": "300 soignants x 8 000 FCFA (sessions modulaires par vagues)"
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.1. Planification et formation continue du personnel soignant et médico-technique",
        "act": "Organiser les sessions sur les techniques de lavage des mains au personnel des services hospitaliers et connexes - Sensibilisation des agents sur les techniques de lavage des mains",
        "resp": "Formateurs internes / EOPCI",
        "per": "Février - Avril 2027",
        "ind_base": "Pratiques empiriques de friction et lavage des mains observées",
        "ind_cible": "100% des agents des unités ciblées sensibilisés et évalués par boîte à coucou / friction",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.2. Formation pratique des agents d'entretien et aides-soignants sur le bionettoyage et la gestion des déchets biomédicaux",
        "act": "3.2.1. Organiser des sessions pratiques de formation des agents d’entretien et aides-soignants sur le bionettoyage et la gestion des déchets hospitaliers :\n- Techniques de bionettoyage (du plus propre vers le plus sale)\n- Dilution et dosage corrects des détergents-désinfectants\n- Gestion sécurisée des excréta et du linge souillé (300 agents ciblés)",
        "resp": "Formateurs internes / EOPCI",
        "per": "Février - Avril 2027",
        "ind_base": "Pratiques empiriques de nettoyage et erreurs fréquentes de dilution",
        "ind_cible": "300 agents d'entretien et aides-soignants formés et évalués sur site",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.3. Éducation sanitaire des usagers et accompagnants",
        "act": "3.3.1. Organiser des séances régulières d'éducation et de sensibilisation sur les pratiques d’hygiène de base pour les patients et les accompagnants :\n- Hygiène des mains et utilisation correcte des distributeurs de savon/PHA\n- Propreté des chambres et tri des déchets ménagers",
        "resp": "EOPCI / Points focaux services / Service social",
        "per": "Continu",
        "ind_base": "Absence de sensibilisation structurée des usagers",
        "ind_cible": "Au moins 2 séances d'éducation tenues par semaine dans les salles d'attente et hospitalisation",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.4. Participation aux congrès scientifiques et journées thématiques",
        "act": "3.3.2. Assurer la participation de la délégation du CHUMEL aux congrès scientifiques de PCI (SB2HPCI / HBEEPTI) (15 membres ciblés)",
        "resp": "DG / Point focal PCI",
        "per": "Mai - Juin 2027",
        "ind_base": "Participation irrégulière aux manifestations scientifiques nationales de PCI",
        "ind_cible": "15 professionnels ayant participé aux congrès avec communications orales/posters",
        "source": "FP",
        "rec": True,
        "bud": 300000,
        "bud_detail": "Forfait frais d'inscription et participation de la délégation"
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "7.3. Journée mondiale de l'hygiène des mains et restitution des données",
        "act": "7.3.1. Faire une journée de l’hygiène des mains (organisation et célébration de la Journée internationale du 5 mai 2027 «Sauvez des vies : nettoyez-vous les mains») :\n- Conférences thématiques et ateliers de démonstration pratique\n- Concours d'émulation du service le plus observant avec remise de prix\n- Distribution de flacons individuels de solution hydro-alcoolique (PHA)\n- Stands d'information grand public et couverture médiatique",
        "resp": "CLIN / EOPCI / DG",
        "per": "Mai 2027",
        "ind_base": "Célébration ponctuelle sans concours d'émulation formalisé",
        "ind_cible": "Journée célébrée, 1 service lauréat primé et 500 flacons individuels de PHA distribués",
        "source": "FP / PTF",
        "rec": True,
        "bud": 500000,
        "bud_detail": "Forfait organisation de la journée, prix d'émulation, supports et flacons PHA"
    },
    {
        "os": "III. FORMATION ET ÉDUCATION EN PCI",
        "inter": "3.4. Participation aux congrès scientifiques et journées thématiques",
        "act": "Participer au congrès de la médecine hospitalière EOPCI",
        "resp": "DG / CLIN / EOPCI",
        "per": "Juillet 2027",
        "ind_base": "Absence d'échanges d'expériences inter-hospitalières récentes",
        "ind_cible": "Délégation CHUMEL ayant présenté un retour d'expérience au congrès",
        "source": "FP",
        "rec": True,
        "bud": 300000,
        "bud_detail": "Forfait inscription et communication scientifique de l'EOPCI"
    },

    # OS V. SURVEILLANCE DES IAS ET ÉCOLOGIE MICROBIENNE
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.1. Dispositif de surveillance épidémiologique des infections associées aux soins",
        "act": "5.1.1. Élaborer, valider et déployer le plan institutionnel de surveillance des Infections Associées aux Soins (IAS) :\n- Définir les protocoles de surveillance ciblée (Infections du Site Opératoire, bactériémies sur cathéter, infections urinaires sur sonde, infections néonatales)\n- Standardiser les fiches de recueil et de notification",
        "resp": "EOPCI / Réanimation / Maternité / Pédiatrie",
        "per": "Novembre - Décembre 2026",
        "ind_base": "Protocole institutionnel de surveillance absent",
        "ind_cible": "Plan et protocoles de surveillance des 4 IAS majeures opérationnels",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.1. Dispositif de surveillance épidémiologique des infections associées aux soins",
        "act": "5.1.2. Organiser des enquêtes épidémiologiques sur les IAS (une enquête dans les départements d’intérêts au CHU-MEL)",
        "resp": "EOPCI / Équipes de soins",
        "per": "Août 2027",
        "ind_base": "Taux de prévalence global des IAS au CHUMEL non réévalué",
        "ind_cible": "1 enquête exhaustive de prévalence réalisée avec rapport épidémiologique diffusé",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.1. Dispositif de surveillance épidémiologique des infections associées aux soins",
        "act": "Organiser la collecte hebdomadaire de données sur les IAS par les points focaux IAS de service",
        "resp": "Points focaux IAS / EOPCI",
        "per": "Continue",
        "ind_base": "Déclaration opportuniste et retardée des cas d'infections",
        "ind_cible": "Fiches de recueil hebdomadaire transmises chaque semaine par 100% des services sentinelles",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.1. Dispositif de surveillance épidémiologique des infections associées aux soins",
        "act": "Faire une analyse hebdomadaire - Présenter les résultats à la réunion hebdomadaire de l’EOPCI",
        "resp": "EOPCI",
        "per": "Continue",
        "ind_base": "Données collectées non synthétisées pour l'action",
        "ind_cible": "Tableau de bord hebdomadaire des IAS examiné à chaque réunion d'équipe",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.2. Microbiologie hospitalière et recherche des germes nosocomiaux",
        "act": "5.2.1. Intégrer les aspects d’analyse microbiologique et de contrôle environnemental dans les activités régulières du laboratoire du CHUMEL :\n- Standardiser les techniques de prélèvement d'air, d'eau et de surfaces\n- Ouvrir un registre dédié aux contrôles bactériologiques d'hygiène",
        "resp": "Chef Service Laboratoire / EOPCI",
        "per": "Mars 2027",
        "ind_base": "Contrôles bactériologiques environnementaux non inscrits dans la routine du laboratoire",
        "ind_cible": "Procédure d'analyse environnementale validée et registre de traçabilité ouvert au laboratoire",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "V. SURVEILLANCE DES IAS",
        "inter": "5.2. Microbiologie hospitalière et recherche des germes nosocomiaux",
        "act": "5.2.2. Exécuter le programme annuel de recherche des germes nosocomiaux et profils de résistance aux antibiotiques (33 processus / séries de prélèvements environnementaux et sentinelles) :\n- Prélèvements de surfaces dans les blocs opératoires, réanimation, néonatologie et biberonnerie\n- Contrôle bactériologique de l'air et de la stérilisation\n- Isolement des bactéries multirésistantes (BMR) et établissement des antibiogrammes\n- Analyser les alertes infectieuses et incidents de la semaine\n- Coordonner les activités de terrain et les supervisions",
        "resp": "Laboratoire de bactériologie / EOPCI",
        "per": "Continu (Octobre 2026 - Septembre 2027)",
        "ind_base": "Données sporadiques d'écologie bactérienne hospitalière",
        "ind_cible": "33 séries de contrôles microbiologiques exécutées avec cartographie complète de l'écologie microbienne du CHUMEL",
        "source": "FP",
        "rec": True,
        "bud": 1000000,
        "bud_detail": "Forfait consommables bactériologiques, milieux de culture et réactifs d'antibiogramme"
    },

    # OS VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.1. Dispositif de mesure, indicateurs et équipements informatiques de suivi-évaluation",
        "act": "7.1.1. Identifier et formaliser les indicateurs clés de suivi de la PCI (taux d'observance de l'hygiène des mains, conformité de pose/entretien des cathéters, conformité de pose des sondes urinaires, respect du tri des DBM, conformité du bionettoyage, taux d'AES)",
        "resp": "EOPCI",
        "per": "Janvier 2027",
        "ind_base": "Absence de liste consensuelle d'indicateurs standardisés",
        "ind_cible": "Répertoire de 6 indicateurs prioritaires formalisé avec fiches de calcul documentées",
        "source": "Néant",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.1. Dispositif de mesure, indicateurs et équipements informatiques de suivi-évaluation",
        "act": "7.1.2. Élaborer, tester et dupliquer les outils et grilles standardisés d'audit clinique et de recueil de données de terrain",
        "resp": "EOPCI",
        "per": "Février 2027",
        "ind_base": "Grilles d'audit disparates non harmonisées",
        "ind_cible": "Kit complet de grilles d'audit clinique validé et disponible sous formats papier et électronique",
        "source": "FP",
        "rec": False,
        "bud": 250000,
        "bud_detail": "Forfait infographie, duplication et reprographie des grilles d'audit clinique"
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.1. Dispositif de mesure, indicateurs et équipements informatiques de suivi-évaluation",
        "act": "7.1.3. Doter l'unité PCI en matériels informatiques et de bureau indispensables au recueil statistique et à la gestion documentaire :\n- 1 Ordinateur portable dédié aux données PCI\n- 1 Imprimante multifonction (impression des grilles et rapports)\n- 1 Disque dur SSD externe 1 To et 1 clé USB 32 Go (sauvegarde et archivage)\n- 1 Armoire de rangement sécurisée des archives du CLIN\n- Fournitures de bureau",
        "resp": "DAF / EOPCI",
        "per": "CONTINUE",
        "ind_base": "Matériels informatiques semi-fonctionnels risquant de céder à tout moment",
        "ind_cible": "Unité PCI dotée d'équipements informatiques et d'une armoire de rangement neufs et fonctionnels",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.2. Évaluations mensuelles et audits cliniques des pratiques de soins",
        "act": "7.2.1. Faire une fois par mois l’évaluation de l’hygiène des mains dans les services de soins (évaluation observationnelle de l'observance sur 500 opportunités par trimestre)",
        "resp": "EOPCI / Points focaux",
        "per": "Mensuel (Oct. 2026 - Sept. 2027)",
        "ind_base": "Taux d'observance initial méconnu ou < 40%",
        "ind_cible": "12 rapports d'évaluation mensuelle ; taux d'observance global cible supérieur à 70%",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.2. Évaluations mensuelles et audits cliniques des pratiques de soins",
        "act": "7.2.3. Réaliser des audits internes PCI trimestriels sur la gestion des cathéters veineux, la gestion des DBM et le bionettoyage dans l'ensemble des services",
        "resp": "EOPCI / CLIN",
        "per": "Trimestriel (Déc. 2026, Mars, Juin, Sept. 2027)",
        "ind_base": "Audits cliniques sporadiques sans planification",
        "ind_cible": "4 rapports d'audit interne produits assortis de plans de correction validés",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.2. Évaluations mensuelles et audits cliniques des pratiques de soins",
        "act": "Realiser un suivi mensuel de la qualité de la gestion des déchets biomédicaux",
        "resp": "EOPCI / Service Salubrité",
        "per": "MENSUEL",
        "ind_base": "Anomalies de tri et de pesée non corrigées rapidement",
        "ind_cible": "12 grilles de contrôle mensuel de la filière DBM renseignées et archivées",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VII. SUIVI, AUDITS ET RESTITUTION DES RÉSULTATS",
        "inter": "7.3. Restitution des audits et feedback aux équipes",
        "act": "7.3.2. Élaborer un plan de restitution des audits aux parties prenantes et animer les réunions trimestrielles de restitution et retour d'information (feedback)",
        "resp": "EOPCI / CLIN",
        "per": "Novembre 2026 puis Trimestriel",
        "ind_base": "Absence de circuit formalisé de feedback des résultats aux équipes soignantes",
        "ind_cible": "Plan de restitution validé et 4 réunions trimestrielles de feedback tenues auprès des chefs de pôles et majors",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },

    # OS VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.1. Charge de travail, dotation en personnel et capacité d'accueil",
        "act": "8.1.1. Faire l’évaluation de la charge de travail, du niveau de dotation en personnel soignant au CHUMEL, ainsi que de l’occupation des lits et de leurs espacements dans les pôles d'hospitalisation",
        "resp": "EOPCI / DSIO / DRH",
        "per": "Septembre 2027",
        "ind_base": "Promiscuité des lits et surcharge de travail non quantifiées objectivement",
        "ind_cible": "Rapport d'évaluation disponible préconisant le respect de l'espacement minimal d'1 mètre et l'adaptation des ratios",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.2. Gestion sécurisée et filière d'élimination des Déchets Biomédicaux (DBM)",
        "act": "8.2.1. Superviser mensuellement la gestion des déchets biomédicaux dans les services (tri à la source, conditionnement en sacs jaunes, pesée/tonnage, transport interne et stockage temporaire)",
        "resp": "EOPCI / Service Salubrité",
        "per": "Mensuel (Continu)",
        "ind_base": "Mélanges fréquents de déchets et ruptures de sacs poubelles",
        "ind_cible": "12 rapports mensuels de supervision ; taux de conformité du tri à la source supérieur à 80%",
        "source": "Néant",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.2. Gestion sécurisée et filière d'élimination des Déchets Biomédicaux (DBM)",
        "act": "8.2.3. superviser la disponibilité des équipements du lavage des mains, du bionetoyage du lavage et sterilisation des linges et équipements médicaux",
        "resp": "DAF / Économat / EOPCI",
        "per": "Novembre - Décembre 2026",
        "ind_base": "Poubelles vétustes, absence de pédale sur plusieurs postes, absence de pesée systématique",
        "ind_cible": "50 poubelles à pédale neuves réparties dans les unités et 1 système de pesage/tonnage fonctionnel",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.2. Gestion sécurisée et filière d'élimination des Déchets Biomédicaux (DBM)",
        "act": "8.2.4. Faire installer un incinérateur hospitalier fonctionnel et de capacité suffisante",
        "resp": "DG / DST / Ministère de la Santé / PTF",
        "per": "Janvier - Août 2027",
        "ind_base": "Traitement non optimal des DBM / incinérateur défaillant",
        "ind_cible": "Dossier technique d'études validé (FP) et incinérateur fonctionnel réceptionné (PTF-État)",
        "source": "FP (études) / PTF-État (travaux)",
        "rec": False,
        "bud": 1000000,
        "bud_detail": "Forfait études techniques préliminaires d'ingénierie et impact environnemental (FP)"
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.3. Eau, assainissement, contrôle des désinfectants et approvisionnement en consommables (WASH)",
        "act": "8.3.1. Vérifier la qualité de l’eau une fois par an (analyses physico-chimiques et bactériologiques des forages, réservoirs de stockage et robinets de soins par un laboratoire agréé)",
        "resp": "EOPCI / DST / Laboratoire d'Hygiène de l'Eau",
        "per": "Mars 2027",
        "ind_base": "Absence de contrôle bactériologique annuel certifié",
        "ind_cible": "Rapport officiel attestant la potabilité de l'eau distribuée délivré et mesures correctives prises",
        "source": "FP",
        "rec": True,
        "bud": 1000000,
        "bud_detail": "Forfait prélèvements et analyses physico-chimiques/bactériologiques laboratoire externe agréé"
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.3. Eau, assainissement, contrôle des désinfectants et approvisionnement en consommables (WASH)",
        "act": "8.3.2. Vérifier la qualité et la concentration des matériels et produits de désinfection (titrage régulier du chlore actif de l'eau de javel et conformité des solutions hydro-alcooliques)",
        "resp": "Pharmacie hospitalière / Laboratoire / EOPCI",
        "per": "Trimestriel (Nov. 2026, Fév., Mai, Août 2027)",
        "ind_base": "Dilutions artisanales non titrées au chloromètre",
        "ind_cible": "4 rapports trimestriels de contrôle de qualité et de titrage du chlore actif validés",
        "source": "FP",
        "rec": True,
        "bud": 500000,
        "bud_detail": "Forfait bandelettes de test, réactifs de chlorométrie et contrôles pharmacotechniques"
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.3. Eau, assainissement, contrôle des désinfectants et approvisionnement en consommables (WASH)",
        "act": "8.3.3. Acquérir et installer 20 dispositifs ergonomiques de lavage des mains avec robinetterie non manuelle (commande au coude ou à pédale) dans les zones critiques dépourvues de points d'eau",
        "resp": "DST / DAF / EOPCI",
        "per": "Décembre 2026 - Mars 2027",
        "ind_base": "Points d'eau insuffisants ou robinets manuels sources de recontamination",
        "ind_cible": "20 nouveaux postes ergonomiques de lavage des mains installés et raccordés au réseau",
        "source": "FP",
        "rec": False,
        "bud": 1000000,
        "bud_detail": "Forfait achat et pose de 20 postes de lavage avec robinetterie commande non manuelle"
    },
    {
        "os": "VIII. CHARGES DE TRAVAIL, DOTATION EN PERSONNEL, GESTION DES DÉCHETS BIOMÉDICAUX ET ENVIRONNEMENT BÂTI (WASH)",
        "inter": "8.3. Eau, assainissement, contrôle des désinfectants et approvisionnement en consommables (WASH)",
        "act": "8.3.4. Superviser  la dotation annuelle en consommables d'hygiène et fournitures ordinaires indispensables au fonctionnement du CLIN/PCI :\n- Savon liquide pour le lavage des mains (250 Litres)\n- Essuie-mains jetables à usage unique (250 rouleaux)\n- Fournitures de bureau annuelles (12 cartons papier RAM, 12 recharges encre imprimante A80, stylos, chemises dossiers, agrafes, registres)",
        "resp": "Économat / DAF / Point focal PCI",
        "per": "Trimestriel (Continu)",
        "ind_base": "Ruptures épisodiques de savon liquide et essuie-mains",
        "ind_cible": "Zéro rupture de stock en savon liquide et essuie-mains constatée dans les blocs et unités critiques",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    },

    # COMMUNICATION SUR LA PCI
    {
        "os": "VI. COMMUNICATION SUR LA PCI",
        "inter": "6.1. Mettre en place des outils de communication de la PCI",
        "act": "ELABORATION DES OUTILS DE COMMUNICATION SUR L’hygiène hospitalière et la PCI (Affiches, affichettes, dépliants)",
        "resp": "EOPCI / Cellule Communication",
        "per": "Février – Mars 2027",
        "ind_base": "Absence de supports visuels harmonisés et validés",
        "ind_cible": "Kit complet de maquettes validé (lavage des mains, DBM, bionettoyage, AES)",
        "source": "FP",
        "rec": False,
        "bud": 500000,
        "bud_detail": "Forfait conception graphique et mise en page des supports visuels PCI"
    },
    {
        "os": "VI. COMMUNICATION SUR LA PCI",
        "inter": "6.1. Mettre en place des outils de communication de la PCI",
        "act": "Multiplication des outils de communication",
        "resp": "Économat / DAF / EOPCI",
        "per": "Mars – Avril 2027",
        "ind_base": "Supports visuels non reproduits à grande échelle",
        "ind_cible": "500 affiches plastifiées et 2 000 dépliants imprimés et réceptionnés",
        "source": "FP",
        "rec": False,
        "bud": 0,
        "bud_detail": ""
    },
    {
        "os": "VI. COMMUNICATION SUR LA PCI",
        "inter": "6.1. Mettre en place des outils de communication de la PCI",
        "act": "Diffuser les outils de communication",
        "resp": "EOPCI / Points focaux de service",
        "per": "Continue",
        "ind_base": "Affichage hétérogène ou dégradé dans les couloirs et services",
        "ind_cible": "100% des postes de soins et lavabos équipés d'affiches visibles et entretenues",
        "source": "FP",
        "rec": True,
        "bud": 0,
        "bud_detail": ""
    }
]

print(f"Loaded {len(PTA_CLIN_REAJUSTE_DATA)} activities.")
